### ISSUE TITLE
ng lint fail in 0.10.1

### ISSUE THREAD

**Issue by cipchk** [es-joy/jsdoccomment#3]
[error] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser/tokenizers/description.js' is not defined by "exports" in /Users/cipchk/Desktop/work/delon/node_modules/@es-joy/jsdoccomment/node_modules/comment-parser/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:437:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/cipchk/Desktop/work/delon/node_modules/@es-joy/jsdoccomment/dist/index.cjs.cjs:7:28)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)

**Comment by brettz9** [comment]
Which version of Node are you using?

**Comment by cipchk** [comment]
Sorry, my mistake, I fixed the problem after upgrading the eslint-plugin-jsdoc latest version.
