### ISSUE TITLE
throws on valid syntax

### ISSUE THREAD

**Issue by Trott** [es-joy/jsdoccomment#8]
This bug does not exist in 0.22.1 but is in 0.28.0.

Code being processed:

```js
(function(exports, require, module, __filename, __dirname) {
// Module code actually lives in here
});
```

Expected result is successful parsing and that's what we see in 0.22.1.

With 0.28.0, we end up with a TypeError:

```
TypeError: Cannot read properties of null (reading 'type')
Occurred while linting /home/runner/work/node/node/doc/api/modules.md/10_10.js:1
Rule: "jsdoc/check-access"
    at getReducedASTNode (/home/runner/work/node/node/tools/node_modules/eslint/node_modules/@es-joy/jsdoccomment/dist/index.cjs.cjs:587:24)
    at *:not(Program) (/home/runner/work/node/node/tools/node_modules/eslint/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:948:67)
    at ruleErrorHandler (/home/runner/work/node/node/tools/node_modules/eslint/lib/linter/linter.js:11[14](https://github.com/nodejs/node/runs/6144635885?check_suite_focus=true#step:5:14):28)
    at /home/runner/work/node/node/tools/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/node/node/tools/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/node/node/tools/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/node/node/tools/node_modules/eslint/lib/linter/node-event-generator.js:324:[22](https://github.com/nodejs/node/runs/6144635885?check_suite_focus=true#step:5:22))
    at NodeEventGenerator.enterNode (/home/runner/work/node/node/tools/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/node/node/tools/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:[23](https://github.com/nodejs/node/runs/6144635885?check_suite_focus=true#step:5:23))
```

References:

* https://github.com/nodejs/node/runs/6144635885?check_suite_focus=true
* https://github.com/nodejs/node/pull/42845#issuecomment-1107713942

**Comment by brettz9** [comment]
Fixed in 92a36cbb42dec715749a9d54251acdf6c14b23ad . I released v0.28.1 but then also released v0.29.0 because I noticed our `engines` wasn't properly reflecting current behavior (that we don't support Node 12).

I've updated `eslint-plugin-jsdoc` to use v0.29.0 as v39.2.8. Closing as should resolve. Thanks for the report!
